package:
  name: olapy
  version: master

source:
  url: https://github.com/abilian/olapy/archive/master.zip


requirements:
  run:
    - pandas
    - xmlwitch
    - attrs
    - regex

test:
  imports:
    - olapy

